<a href="https://colab.research.google.com/github/adesiji007/Amaze-File-Manager/blob/master/NeuralNetworkParameter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

Define your Neural network Model

In [2]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    # This model has no layers
  def forward(self, x):
    # This model does not forward anything
    return x

Instantiate your model

In [4]:
# creating your model object
model = myFirstNeuralNetworkModel()

In [5]:
print(model)

myFirstNeuralNetworkModel()


# Define your input tensor data:
. Total 100 records

1.   100 records of 5 columns or dimensions
2.   100 x [age, income, zip-code, has_house, is_married]
3. The outcome is purchase_house = True or False / 1 or 0
4. Each record has 5 dimensions or fields

In [8]:
t = torch.randn(10, 5)
print(t.shape)
print(t.dtype)
print(t.size)
print(t)

torch.Size([10, 5])
torch.float32
<built-in method size of Tensor object at 0x7da6043e6250>
tensor([[ 2.0859e-01, -1.6950e+00,  4.1612e-01, -6.5064e-01, -3.6443e-01],
        [ 1.7204e+00, -1.6807e-01, -3.5706e-02, -1.4623e+00,  5.4238e-01],
        [-2.8408e+00, -4.6982e-01,  3.4405e-01, -4.5144e-01,  4.1577e-01],
        [ 1.8253e+00,  1.0282e+00, -3.7636e-01,  1.0342e+00,  5.2937e-01],
        [ 5.2646e-01, -2.2880e-01, -1.4399e+00, -1.9204e+00,  7.8542e-01],
        [-1.7097e-01,  7.7035e-01, -7.3978e-02, -2.1601e-01, -5.6168e-01],
        [-1.1882e+00,  2.0695e-02,  7.5631e-01,  1.0309e+00,  1.4614e+00],
        [ 1.3704e+00, -4.3049e-04, -1.5694e+00,  7.8156e-01, -1.2277e+00],
        [-6.3961e-01,  3.9215e-01, -1.4836e-01,  1.8719e+00,  1.3304e+00],
        [ 6.8807e-01, -3.0473e-01, -2.0973e-01,  1.3169e+00,  3.9841e-01]])


# Create an object by passing input data through the model

In [9]:
nnm = model(t)

In [10]:
print(model(t))

tensor([[ 2.0859e-01, -1.6950e+00,  4.1612e-01, -6.5064e-01, -3.6443e-01],
        [ 1.7204e+00, -1.6807e-01, -3.5706e-02, -1.4623e+00,  5.4238e-01],
        [-2.8408e+00, -4.6982e-01,  3.4405e-01, -4.5144e-01,  4.1577e-01],
        [ 1.8253e+00,  1.0282e+00, -3.7636e-01,  1.0342e+00,  5.2937e-01],
        [ 5.2646e-01, -2.2880e-01, -1.4399e+00, -1.9204e+00,  7.8542e-01],
        [-1.7097e-01,  7.7035e-01, -7.3978e-02, -2.1601e-01, -5.6168e-01],
        [-1.1882e+00,  2.0695e-02,  7.5631e-01,  1.0309e+00,  1.4614e+00],
        [ 1.3704e+00, -4.3049e-04, -1.5694e+00,  7.8156e-01, -1.2277e+00],
        [-6.3961e-01,  3.9215e-01, -1.4836e-01,  1.8719e+00,  1.3304e+00],
        [ 6.8807e-01, -3.0473e-01, -2.0973e-01,  1.3169e+00,  3.9841e-01]])


In [11]:
print(nnm)

tensor([[ 2.0859e-01, -1.6950e+00,  4.1612e-01, -6.5064e-01, -3.6443e-01],
        [ 1.7204e+00, -1.6807e-01, -3.5706e-02, -1.4623e+00,  5.4238e-01],
        [-2.8408e+00, -4.6982e-01,  3.4405e-01, -4.5144e-01,  4.1577e-01],
        [ 1.8253e+00,  1.0282e+00, -3.7636e-01,  1.0342e+00,  5.2937e-01],
        [ 5.2646e-01, -2.2880e-01, -1.4399e+00, -1.9204e+00,  7.8542e-01],
        [-1.7097e-01,  7.7035e-01, -7.3978e-02, -2.1601e-01, -5.6168e-01],
        [-1.1882e+00,  2.0695e-02,  7.5631e-01,  1.0309e+00,  1.4614e+00],
        [ 1.3704e+00, -4.3049e-04, -1.5694e+00,  7.8156e-01, -1.2277e+00],
        [-6.3961e-01,  3.9215e-01, -1.4836e-01,  1.8719e+00,  1.3304e+00],
        [ 6.8807e-01, -3.0473e-01, -2.0973e-01,  1.3169e+00,  3.9841e-01]])


In [13]:
from torch._C import Size
print(nnm.size)

<built-in method size of Tensor object at 0x7da6043e6250>


In [15]:
print(nnm.shape)

torch.Size([10, 5])


In [ ]:
nnm

Until now we have no relationship between the Tensor and the Model we created.


1.   The Model definition is empty, it does not not handle the input as there are no layers to process the input data
2.   The forward method does not pass anything
3. The model is EMPTY

# Lets connect the model and Input data (Tensor) together

# Concept:

*   Dataset:

  *   We have to records of 5 dimensions
  *   We use 10 records as it easy to visualize here
  *   Our output class has 2 values True (1) or False (0)
*   Layers
  *   We will add through experimentation

*   A network with input and output layers:
  *   First (Input and Output) Layer
    *   self.lin1 = nn.Linear(Input_dimensions, output_classes)
    *   Applies a linear transformation to the incoming data y = zA^t + b
    *   















In [16]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear0 = nn.Linear(5, 2)
  def forward(self, x):
    x = self.linear0(x)
    print(x.shape)
    return x

# A Network with N hidden layer(s)

  *   First(Input) Layer
    *   self.linY = nn.Linear(input_dimensions, input_for_first_hidden_layer)
*   Middle Layers(As many as needed)
    *   Must have the matrix manipulations working..
*   Last(Output) Layer
    *   self.linX = nn.Linear(output_of_previous_layers, out_classes)



In [18]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear0 = nn.Linear(5, 15)
    self.linear1 = nn.Linear(10, 2)
  def forward(self, x):
    x = self.linear0(x)
    print(x.shape)
    x = self.linear1(x )
    print(x.shape)
    return x

In [19]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    self.linear0 = nn.Linear(5, 100)
    self.linear1 = nn.linear(100, 10)
    self.linear2 = nn.Linear(10, 2)
  def forward(self, x):
    x = self.linear0(x)
    print(x.shape)
    x = self.linear1(x)
    print(x.shape)
    x = self.linear2(x + x + x)
    print(x.shape)
    return x

In [35]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    self.linear0 = nn.Linear(5, 100)
    self.linear1 = nn.linear(1000, 100)
    self.linear2 = nn.Linear(100, 10)
    self.linear3 = nn.Linear(10, 2)
  def forward(self, x):
    x = self.linear0(x)
    print(x.shape)
    x = self.linear1(x)
    print(x.shape)
    x = self.linear2(x)
    print(x.shape)
    x = self.linear3(x)
    print(x.shape)
    return x

# Lets Experimant with out Neural with various Hidden Layers

In [57]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    # first layer takes the input of size 5 and
    ## first layer INPUT parameter shows the number of dimensions in your data as input to the network
    self.linear1 = nn.Linear(5, 10)
    self.linear2 = nn.Linear(10, 100)
    self.linear3 = nn.Linear(100, 100)
    self.linear4 = nn.Linear(100, 100)
    self.linear5 = nn.Linear(100, 2)
    ## Last layer OUT parameter shows the number of outputs in your neural network
  def forward(self, x):
    # This model connect the layer outputs in the forward pass
    x1 = self.linear1(x)
    print(x.shape)
    x = self.linear2(x1)
    print(x.shape)
    x = self.linear3(x) + self.linear2(x1)
    print(x.shape)
    x = self.linear4(x)
    print(x.shape)
    x = self.linear5(x)
    print(x.shape)
    return x

In [58]:
#t = torch.randn(10, 5)
#t = torch.ones(10, 5)
t = torch.zeros(10, 5)

print(t.shape)
print(t.dtype)
print(t.size)
print(t)


torch.Size([10, 5])
torch.float32
<built-in method size of Tensor object at 0x7da5fabf9440>
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [59]:
model = myFirstNeuralNetworkModel()
n = model(t)

torch.Size([10, 5])
torch.Size([10, 100])
torch.Size([10, 100])
torch.Size([10, 100])
torch.Size([10, 2])


In [60]:
print(n.size)
print(n.shape)
print(n)

<built-in method size of Tensor object at 0x7da5fabe11c0>
torch.Size([10, 2])
tensor([[ 0.0070, -0.1090],
        [ 0.0070, -0.1090],
        [ 0.0070, -0.1090],
        [ 0.0070, -0.1090],
        [ 0.0070, -0.1090],
        [ 0.0070, -0.1090],
        [ 0.0070, -0.1090],
        [ 0.0070, -0.1090],
        [ 0.0070, -0.1090],
        [ 0.0070, -0.1090]], grad_fn=<AddmmBackward0>)


# importance of your model size:


*   The size must be:
  *   [The total number of the records, total number of output class]
  



In [ ]:
print(n.shape)

# Comples Forward Functions

In [ ]:
def forward(self, x):
  x1 = self.linear1(x)
  x2 = x + self.linear2(x1)
  x2 = self.linear1(x1)
  x = self.linear3(x2 + 1)
  return x

In [66]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    #This model has 2 Linear layers
    self.linear1 = nn.Linear(5, 100)
    self.linear2 = nn.Linear(100, 5)
    self.linear3 = nn.Linear(100, 2)
    ## Last layer OUT parameter shows the number of outputs in your neural network
  def forward(self, x):
    # This model connect the layer output in the forward pass
    x1 = self.linear1(x) # in -> 5, 100, x1 = 5,100
    print(x1.shape)
    x2 = x + self.linear2(x1) # (5, 100) + (5, 100) > x2 = (5, 100)
    print(x2.shape)
    x2 = self.linear1(x2) # x2 => (5, 100)
    print(x2.shape)
    x = self.linear3(x2) # x2 = (5, 100), x3 => (100, 2) > x = output dimension: 2
    print(x.shape)
    return x


In [67]:
model = myFirstNeuralNetworkModel()
#t = torch.ones(10, 5)
t = torch.randn(10, 5)
n = model(t)

torch.Size([10, 100])
torch.Size([10, 5])
torch.Size([10, 100])
torch.Size([10, 2])


In [68]:
print(n.size)
print(n.shape)
print(n)

<built-in method size of Tensor object at 0x7da5facdac00>
torch.Size([10, 2])
tensor([[ 0.2494,  0.0575],
        [-0.1559,  0.8767],
        [-0.0951,  0.4863],
        [-0.1233,  0.4867],
        [-0.4218,  0.8940],
        [ 0.0918, -0.1910],
        [-0.7302,  0.9222],
        [-0.7705, -0.0519],
        [ 0.2020,  1.4065],
        [ 0.2395,  1.1905]], grad_fn=<AddmmBackward0>)


#Heart Disease Problem

*   https://archive.ics.uci.edu/ml/datasets/heart+disease
*   75 columns, 14 columns are most used and applicable
*   Records 303
*   Input -> (303, 14)
*   Output -> 2 classes -> True or False
*   List item




In [70]:
import pandas as pd
import numpy as np

In [74]:
df = pd.read_csv('https://raw.githubusercontent.com/prodramp/publiccode/master/datasets/heart.csv')

In [75]:
df_input = pd.DataFrame(df.iloc[:, 0:13])
df_target = pd.DataFrame(df.iloc[:, 13], columns=['target'])

In [76]:
df_input.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal'],
      dtype='object')

In [77]:
df_input

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [78]:
df_target.columns

Index(['target'], dtype='object')

In [87]:
df_target

target
0         1
1         1
2         1
3         1
4         1
..      ...
298       0
299       0
300       0
301       0
302       0

[303 rows x 1 columns]

In [88]:
inputs_np_array = df_input.to_numpy()
targets_np_array = df_target.to_numpy()

In [89]:
inputs_np_array

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.]])

In [90]:
#targets_np_array

In [92]:
inputs = torch.from_numpy(np.array(inputs_np_array, dtype='float32'))
targets = torch.from_numpy(np.array(targets_np_array, dtype='float32'))

In [93]:
print(inputs.dtype)
inputs

torch.float32


tensor([[63.,  1.,  3.,  ...,  0.,  0.,  1.],
        [37.,  1.,  2.,  ...,  0.,  0.,  2.],
        [41.,  0.,  1.,  ...,  2.,  0.,  2.],
        ...,
        [68.,  1.,  0.,  ...,  1.,  2.,  3.],
        [57.,  1.,  0.,  ...,  1.,  1.,  3.],
        [57.,  0.,  1.,  ...,  1.,  1.,  2.]])

In [94]:
print(targets.dtype)
#target

torch.float32


In [95]:
print(len(inputs[0]))
print(len(targets[0]))
print(len(inputs))
print(len(targets))

13
1
303
303


In [112]:
class HeartDiseaseNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    ## 13 input field will be used a feature, 100 is the hidden layer
    self.linear1 = nn.Linear(13, 100)
    self.linear2 = nn.Linear(100, 10)
    self.linear3 = nn.Linear(10, 2)
  def forward(self, x):
    x = self.linear1(x)
    print(x.shape)
    x = self.linear2(x)
    print(x.shape)
    x = self.linear3(x)
    print(x.shape)
    return x

In [113]:
hmodel = HeartDiseaseNeuralNetworkModel()

In [114]:
t = torch.randn(303, 13)
print(t.size)
print(t.shape)
print(t)

<built-in method size of Tensor object at 0x7da5fa33bb00>
torch.Size([303, 13])
tensor([[-0.6273, -0.0633, -1.5067,  ...,  0.4434,  0.5599, -0.2937],
        [ 0.5962, -0.8362,  0.7517,  ..., -0.5551, -0.2771, -1.3007],
        [-2.4575, -1.1284,  1.2383,  ..., -0.0532, -1.8601, -0.9602],
        ...,
        [-0.9004,  0.3999, -0.8771,  ..., -0.0858,  1.3213, -1.6004],
        [-0.6123,  0.9187, -0.8749,  ...,  0.1562,  1.9772,  0.6842],
        [ 0.0870,  0.2418, -0.5100,  ...,  0.9767,  1.2105, -1.1037]])


In [115]:
hm = hmodel(t)
#hm

torch.Size([303, 100])
torch.Size([303, 10])
torch.Size([303, 2])


In [116]:
hm.shape

torch.Size([303, 2])

# MNIST Problom
  *    http://yann.lecun.com/exdb/mnist/
  *    60000 records with 28x28 images means -60,000 images with 784
  *   Input -> (60000, 784)
  *   Out -> 10 classes -> 0 to 9 digitas




In [121]:
import torch
import torch.nn as nn

In [129]:
class MNISTNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    # 13 input fields will be used a feature, 100 is the hidden layer
    self.linear1 = nn.Linear(784, 1000)
    self.linear2 = nn.Linear(1000, 100)
    self.linear3 = nn.Linear(100, 10)
    self.linear4 = nn.Linear(10, 10)
  def forward(self, x):
    x = self.linear1(x)
    print(x.shape)
    x = self.linear2(x)
    print(x.shape)
    x = self.linear3(x)
    print(x.shape)
    x = self.linear4(x)
    print(x.shape)
    return x

In [130]:
mnist_model = MNISTNeuralNetworkModel()

In [131]:
t = torch.randn(60000, 28*28)
print(t.size)
print(t.shape)
print(t)


<built-in method size of Tensor object at 0x7da5fabfa2f0>
torch.Size([60000, 784])
tensor([[-0.5226,  0.1526,  0.2450,  ...,  1.4973, -0.1384, -0.0592],
        [ 0.3246, -0.4425,  0.4365,  ...,  0.1504,  2.0678,  0.7126],
        [ 0.8928, -1.0750,  1.4245,  ...,  2.8937, -0.2091, -0.6694],
        ...,
        [ 0.7765, -0.7227,  1.1867,  ...,  0.5019,  1.6947,  2.0049],
        [-0.6238, -0.7462, -1.3786,  ..., -0.1113, -0.1394,  1.0458],
        [ 0.0306, -2.2686, -0.1752,  ..., -0.9635, -0.3883, -0.5464]])


In [132]:
mn = mnist_model(t)

torch.Size([60000, 1000])
torch.Size([60000, 100])
torch.Size([60000, 10])
torch.Size([60000, 10])


In [133]:
mn.shape

torch.Size([60000, 10])

# Using nn.Parameters
Parameters are Tensor subclasses, that have a very special property when used with Module - when they're assigned as module attributes they are automatically added to the list parameters, and will appear in parameters()iterator

*   source:
  *   https://www.kdnuggets.com/2020/09/most-complete-guide-pytorch-data-scientists.html

# Custom Linear Layer


In [74]:
import torch
import torch.nn as nn

In [84]:
class myCustomerLinearLayer(nn.Module):
    def __init__(self, in_size, out_size):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(in_size, out_size))
        self.bias = nn.Parameter(torch.zeros(out_size))

    def forward(self, x):
      print(" weights Shape: ", self.weights.shape)
      print(" Bias Shape: ", self.bias.shape)
      return x.mm(self.weights) + self.bias

# Customer Neural Network

In [85]:
class myCustomNeuralNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.lin1 = myCustomerLinearLayer(784, 10)  # Adjust the input size

    def forward(self, x):
        x = self.lin1(x)
        print(x.shape)
        return x

In [86]:
# Input: 100 records of dimensions 784
x = torch.randn((100, 784))

In [87]:
# Define the model
model = myCustomNeuralNet()

In [88]:
model(x)

 weights Shape:  torch.Size([784, 10])
 Bias Shape:  torch.Size([10])
torch.Size([100, 10])


tensor([[ 3.3110e-01, -2.0924e+01, -3.2166e+01,  6.5045e+00,  3.2366e+01,
          3.6833e+00,  2.7226e+01, -7.7774e-01,  3.5239e+01, -1.6868e+01],
        [-9.2102e+00, -4.5902e+01, -1.9656e+01, -3.0918e+00, -6.7738e+01,
         -2.9155e+00, -2.6896e+01, -3.8674e+01,  1.3331e+01,  1.5959e+01],
        [-2.4977e+01, -3.4876e+01, -1.4650e+01, -2.7795e+01,  2.1991e+01,
         -4.2140e+01, -1.7736e+00,  1.2261e+01, -1.0993e+01,  1.0930e+01],
        [ 4.7138e+01,  3.2648e+00, -2.2819e+01,  1.2349e+01,  1.0493e+01,
         -3.5175e+01, -6.3644e+00, -3.8239e+00, -1.3791e+01,  5.6068e+00],
        [-4.2811e+00, -3.0722e+00,  5.3636e+00,  1.3219e+01, -5.5361e+00,
         -4.2551e+00, -5.0799e+00,  3.9320e+01, -7.9958e+00,  1.5289e+01],
        [ 2.1774e+01,  4.1135e+01,  2.0965e+01,  3.1222e+01, -9.5659e+00,
          8.7935e+00,  5.7746e+00, -1.9918e+01,  1.0317e+01,  3.1214e+01],
        [-8.4625e+00, -5.3550e+00,  3.1182e+01, -7.1349e+01,  1.8269e+01,
         -4.2095e+01,  1.7367e+0

In [89]:
mm = model(x)


 weights Shape:  torch.Size([784, 10])
 Bias Shape:  torch.Size([10])
torch.Size([100, 10])


In [90]:
mm.size()

torch.Size([100, 10])

In [91]:
mm.shape

torch.Size([100, 10])

In [92]:
class myCrazyNeuralNet(nn.Module):
  def __init__(self):
    super().__init__()
    # Define all Layers Here
    self.lin1 = nn.Linear(788, 30)
    self.lin2 = nn.Linear(30, 784)
    self.line3 = nn.Linear(30, 10)


In [93]:
import torch
import torch.nn as nn

class myCustomerLinearLayer(nn.Module):
    def __init__(self, in_size, out_size):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(in_size, out_size))
        self.bias = nn.Parameter(torch.zeros(out_size))

    def forward(self, x):
        return x.mm(self.weights) + self.bias

class myCustomNeuralNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.lin1 = myCustomerLinearLayer(784, 10)  # Adjust the input size

    def forward(self, x):
        x = self.lin1(x)
        print(x.shape)
        return x

# Input: 100 records of dimensions 784
x = torch.randn((100, 784))

# Define the model
model = myCustomNeuralNet()

model(x)


torch.Size([100, 10])


tensor([[ 2.0591e+01, -3.1537e+01, -1.7667e+00, -1.2647e+01,  5.8561e+01,
         -1.7585e+01,  1.5893e+01,  7.9093e+00,  5.2589e+01, -4.4071e+01],
        [-3.8818e+01, -1.3759e+00, -2.2998e+01,  3.6576e+01, -1.6008e+01,
          1.8117e+01,  2.2479e+01, -3.7675e+01, -7.5605e+00,  2.3523e+01],
        [ 3.6988e+01, -1.4129e-01,  3.3830e+01, -2.1945e+01, -6.1704e+01,
          2.3504e+01,  3.6632e+00, -1.8091e+01, -3.4311e+01, -8.7798e+00],
        [ 1.9666e+00, -1.3112e+01,  1.5496e+01, -2.1449e+01,  2.7214e+01,
         -1.0266e+01,  2.1534e+01, -3.2413e-01,  6.8455e+01,  4.9255e+00],
        [-3.3203e+01,  2.7281e+01,  6.5451e+00,  5.2729e+00, -2.1861e+00,
          1.6094e+01,  2.2574e+01,  2.7326e+01, -1.4769e+01,  1.9765e+01],
        [-4.6432e+00,  1.2082e+01, -5.4680e+01,  1.0645e+01, -9.6533e+00,
         -6.4005e+00,  9.4817e+00, -1.9652e+01, -3.4650e+00, -1.2257e+01],
        [ 1.5888e+01,  3.5970e+01,  3.7234e+01,  2.4955e+01,  1.3322e+01,
          2.4594e+00, -3.4067e+0

# Home Work:
Understanding Datasets and Setting as input and output


*   Titanic:
  *   https:///www.kaggle.com/c/titanic
  *   input - 12 columns including survived (output) columns
  *   Output - Survived/Not Survived -> T/F || 1/0
  *   891 records
*   Supermarket
*   Loan Dataset


#*   What is next?


*   How the data is loaded into a network?
*   How transectional data is processed with PyTorch
*   How the image data is processed with PyTorch

# Supported Neural Network Architecture with PyTorch
*   nn.Linear
*   nn.Conv2d
*   nn.MaxPool2d
*   nn.ReLU
*   nn.BatchNorm2d
*   nn.Dropout
*   nn.Embedding
*   nn.MultiheadAttention
*   nn.TransformerEncoder








